apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tonjw23bj-nodejs-gitops
  description: This is GitOps manifest for tonjw23bj-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=tonjw23bj-nodejs
    backstage.io/kubernetes-id: tonjw23bj-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/tonjw23bj-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tonjw23bj-nodejs
